[package]
name = "delphinus-zkwasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmi = { path = "./wasmi" }
wabt = "0.10.0"
